---
- name: Update system
  hosts: localhost
  tasks:
    - debug:
        msg: "Distribution: '{{ ansible_distribution }}'"

    - set_fact:
        commands: []

    # Update according to local package manager
    - set_fact:
        commands: '{{ commands + ["apt dist-upgrade"] }}'
      when: ansible_distribution == 'Ubuntu'

    - set_fact:
        commands: '{{ commands + ["pacman -Syu"] }}'
      when: ansible_distribution == 'Archlinux'

      # Upgrade python pip packages
    - name: Check for pip
      command: which pip
      register: which_pip
      changed_when: false
      failed_when: false

    - set_fact:
        commands: '{{ commands + ["pip list --outdated --format=freeze | cut -d= -f1 | xargs -n1 pip install -U"] }}'
      when: which_pip.stdout != ''

    - debug:
        msg: '{{ ["Run these commands to perform an update:"] + commands }}'
