- name: Install i3 window manager
  include_tasks: '{{ ansible_distribution }}.yml'

- name: Create .myansible directory
  file:
    path: '~/.myansible'
    state: directory

- name: Install post-start exec script
  copy:
    src: i3-poststart.sh
    dest: '~/.myansible/i3-poststart.sh'
    mode: preserve

- name: Create bin directory
  file:
    path: '~/bin'
    state: directory

- name: Install i3-helper
  copy:
    src: i3-helper
    dest: '~/bin/i3-helper'
    mode: preserve

- name: Create config directory
  file:
    path: '~/.config/i3'
    state: directory

- name: Install config
  copy:
    src: config
    dest: '~/.config/i3/config'
    backup: yes

- name: Install xinitrc
  copy:
    src: xinitrc
    dest: '~/.xinitrc'
    backup: yes
