- name: Install i3 window manager
  include_tasks: '{{ ansible_distribution }}.yml'

- name: Create .myansible directory
  file:
    path: '~/.myansible'
    state: directory

- name: Install post-start exec script
  copy:
    src: i3-poststart.sh
    dest: '~/.myansible/i3-poststart.sh'
    mode: preserve
    backup: yes
