- block:
    - name: Create install path
      file:
        path: '{{ gcloud_sdk_install_path }}'
        state: directory

    - name: Download SDK tarball
      get_url:
        url: '{{ gcloud_tarball_url }}'
        dest: '{{ gcloud_sdk_install_path }}'

    - name: Extract tarball
      unarchive:
        src: '{{ gcloud_sdk_install_path }}/{{ gcloud_tarball_url | basename }}'
        dest: '{{ gcloud_sdk_install_path }}'
        extra_opts:
          - --strip-components=1

    - name: Run installer
      shell: '{{ gcloud_sdk_install_path }}/install.sh --quiet'

    - name: Add cloud sdk bin to PATH
      lineinfile:
        path: ~/.bashrc
        line: 'PATH="$PATH:{{ gcloud_sdk_install_path }}/bin"'

    - name: Add autocomplete for utilities
      lineinfile:
        path: ~/.bashrc
        line: '. {{ gcloud_sdk_install_path }}/completion.bash.inc'

  rescue:
    - name: Remove install directory
      file:
        path: '{{ gcloud_sdk_install_path }}'
        state: absent

    - fail:
        msg: Failed to install SDK
