#!/bin/bash

# Check headless branch for any deviation from graphical branch

warn_merge=".warn_merge"

find . -path ./.git -prune -o -type f | while read -r file; do
	if [ "$(git diff graphical -- "$file")" ]; then
		headless_time="$(git log -1 --format=%ct -- "$file")"
		graphical_time="$(git log -1 --format=%ct graphical -- "$file")"
		if [ -z "$graphical_time" ]; then
			echo "$file is new"
			touch "$warn_merge"
		elif [ "$graphical_time" -gt "$headless_time" ]; then
			echo "WARNING: $file has been modified in graphical branch"
		elif [ "$graphical_time" -lt "$headless_time" ]; then
			echo "$file is newer"
			touch "$warn_merge"
		else
			echo "$file differs, but committer times are equal?"
			echo "Inspect with:"
			echo "    git diff graphical -- \"$file\""
		fi
	fi
done

if [ -f "$warn_merge" ]; then
	echo
	echo "headless has updates to merge. Please update graphical branch:"
	echo "    git checkout graphical"
	echo "    git merge headless"
	rm "$warn_merge"
fi
