#!/bin/bash

usage() {
cat <<EOF

Copy locally and source:

    source "\$(dirname \$0)/test_functions"

Variables:

    WORKSPACE  disposable directory cleared before each test
	PASS  return this for success
    FAIL  return this for failure

Functions:

    run <function> <prompt>

        function  test to run. Return 0 for pass, 1 otherwise
        prompt  string to introduce the test

EOF
}

if [ "${BASH_SOURCE[0]}" == "$0" ]; then
	usage
	exit
fi

# Disposable testing directory
WORKSPACE="$(mktemp -d)"

_TESTS_TOTAL=0
_TESTS_PASS=0

# Useful as more intuitive returns
PASS=0
FAIL=1

_RED=
_GREEN=
_CLEAR=
if test -t 1; then
	_RED="\e[31m"
	_GREEN="\e[32m"
	_CLEAR="\e[0m"
fi

run() {
	local func="$1"
	local prompt="$2"

	rm --recursive --force $WORKSPACE/*

	echo -ne "$prompt \t"
	((_TESTS_TOTAL++))

	if eval "$func"; then
		echo -e "$_GREEN[PASS]$_CLEAR"
		((_TESTS_PASS++))
	else
		echo -e "$_RED[FAIL]$_CLEAR"
	fi
}

_exit() {
	echo "$_TESTS_PASS/$_TESTS_TOTAL tests passed"
	rm -rf "$WORKSPACE"
	exit "$((_TESTS_TOTAL-_TESTS_PASS))"
}
trap _exit EXIT
