#!/bin/bash

usage() {
	cat <<-EOF
		Usage:
	EOF
}

connect() {
	local conf="$(mktemp)"

	cat <<-EOF > "$conf"
		network={
		    ssid="$SSID"
			psk="$PSK"
		}
	EOF

	if ! wpa_supplicant -B -i$IFACE -c$conf -D$DRIVER; then
		echo "Failed to start wpa_supplicant"
		return 1
	fi

	if ! dhclient $IFACE; then
		echo "Failed to get an IP address from dhcp"
		return 1
	fi

	return 0
}

SSID=
PSK=
IFACE="wlan0"
DRIVER="wext"

while true; do
	case "$1" in
		--help|-help)
			usage
			exit
		*)
			if [ "$1" ]; then
				ESSID="$1"
			fi
			break
			;;
	esac
	shift
done
