- name: Install distribution-specific system administration utilities
  include_tasks: '{{ ansible_distribution }}.yml'

- include_role: name=gcloud

- name: Install clusterssh config
  copy:
    src: clusterssh-config
    dest: '~/.clustterssh/config'
    backup: yes
